# -*- coding: utf-8 -*-
"""Lab_aula7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cs4jwwJRym_oL3WCtLbScrI2WAPuYA7H
"""

# =====================================================================
# LAB 1: NLU BANCÁRIO COM REGRESSÃO LOGÍSTICA
# =====================================================================

import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

dados_treino = [
    ("Quero sacar 100 reais", "saque"),
    ("Preciso retirar 50 reais", "saque"),
    ("Quero fazer um deposito", "deposito"),
    ("Como faco para depositar dinheiro", "deposito"),
    ("Quero consultar meu saldo", "consultar_saldo"),
    ("Quanto tenho na minha conta", "consultar_saldo"),
    ("Qual o horario de atendimento", "fora_escopo"),
    ("Onde fica a agencia", "fora_escopo")
]

stopwords = ["o", "a", "e", "do", "da", "para", "de", "meu", "minha", "na"]

# 1. PRÉ-PROCESSAMENTO
def pré_processar(texto):
    texto_limpo = re.sub(r'[^\w\s]', '', texto.lower()).strip()
    tokens = texto_limpo.split()

    # TODO 1.1
    tokens_filtrados = [token for token in tokens if token not in stopwords]

    return " ".join(tokens_filtrados)

X_treino_limpo = [pré_processar(item[0]) for item in dados_treino]
y_treino = [item[1] for item in dados_treino]

# 2. VETORIZAÇÃO E TREINAMENTO
vectorizer = TfidfVectorizer()

# TODO 1.2
X_vetorizado = vectorizer.fit_transform(X_treino_limpo)

modelo = LogisticRegression()
modelo.fit(X_vetorizado, y_treino)

# 3. EXTRAÇÃO DE ENTIDADE (REGEX)
def extrair_valor_reais(texto_original):
    match = re.search(r'(\d+)\s*reais', texto_original, re.IGNORECASE)

    # TODO 1.3
    return float(match.group(1)) if match else None

# 4. PIPELINE NLU
def processar_nlu(mensagem_usuario, threshold=0.55):
    texto_p = pré_processar(mensagem_usuario)
    vetor_input = vectorizer.transform([texto_p])

    probas = modelo.predict_proba(vetor_input)[0]

    # TODO 1.4
    maior_confianca = max(probas)
    intencao_prevista = modelo.classes_[probas.argmax()]

    # TODO 1.5
    if maior_confianca < threshold or intencao_prevista == "fora_escopo":
        return {
            "status": "FALLBACK",
            "mensagem": "Não consegui identificar sua solicitação com segurança."
        }
    else:
        return {
            "status": "SUCESSO",
            "intencao": intencao_prevista,
            "confianca": float(maior_confianca),
            "valor": extrair_valor_reais(mensagem_usuario)
        }


# --- TESTE 1 ---
if __name__ == "__main__":
    print(processar_nlu("Quero sacar 200 reais"))

# =====================================================================
# LAB 2: TRIAGEM DE CHAMADOS COM NAIVE BAYES
# =====================================================================

import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

dados_treino = [
    ("Urgente: o servidor caiu e a aplicacao esta fora", "incidente_critico"),
    ("Erro grave no banco de dados e sistema parou", "incidente_critico"),
    ("Como faco para alterar minha senha do e-mail", "duvida_suporte"),
    ("Qual o procedimento para solicitar novo mouse", "duvida_suporte"),
    ("Gostaria de saber o horario de funcionamento", "fora_escopo")
]

stopwords = ["o", "a", "e", "do", "da", "para", "de"]

# 1. PRÉ-PROCESSAMENTO
def pré_processar(texto):
    texto_limpo = re.sub(r'[^\w\s]', '', texto.lower()).strip()
    tokens = texto_limpo.split()

    # TODO 2.1: Filtre as stopwords mantendo os tokens válidos
    tokens_filtrados = [token for token in tokens if token not in stopwords]

    return " ".join(tokens_filtrados)

X_treino_limpo = [pré_processar(item[0]) for item in dados_treino]
y_treino = [item[1] for item in dados_treino]

# 2. VETORIZAÇÃO E TREINAMENTO (NAIVE BAYES)
vectorizer = TfidfVectorizer()
X_vetorizado = vectorizer.fit_transform(X_treino_limpo)

# TODO 2.2: Instancie o modelo Naive Bayes (MultinomialNB)
modelo_nb = MultinomialNB()

# TODO 2.3: Treine o modelo com X_vetorizado e y_treino
# TODO 2.3: Chame o método fit() aqui
modelo_nb.fit(X_vetorizado, y_treino)

# 3. EXTRAÇÃO DE ENTIDADE (CÓDIGO DE PROTOCOLO)
def extrair_protocolo(texto):
    # Procura um padrão de protocolo como 'INC-1234' ou 'INC1234'
    match = re.search(r'INC-?\d{4}', texto, re.IGNORECASE)

    # TODO 2.4: Retorne a string do protocolo encontrado (match.group(0)) em maiúsculas ou None
    return match.group(0).upper() if match else None

# 4. PIPELINE NLU
def processar_triagem(mensagem_usuario, threshold=0.60):
    texto_p = pré_processar(mensagem_usuario)
    vetor_input = vectorizer.transform([texto_p])

    # Naive Bayes também possui .predict_proba()
    probas = modelo_nb.predict_proba(vetor_input)[0]

    maior_confianca = max(probas)
    intencao_prevista = modelo_nb.classes_[probas.argmax()]

    # TODO 2.5: Retorne dicionário de FALLBACK se maior_confianca < threshold
    # Caso contrário, retorne SUCESSO com a intenção, confiança e o código do protocolo extraído
    # TODO 2.5: Escreva a condicional if/else abaixo

    if maior_confianca < threshold:
        return {
            "status": "fallback",
            "mensagem": "Não foi possível classificar o chamado."
        }
    else:
        return {
            "status": "sucesso",
            "intencao": intencao_prevista,
            "confianca": round(maior_confianca, 2),
            "protocolo": extrair_protocolo(mensagem_usuario)
        }

# --- TESTE 2 ---
if __name__ == "__main__":
    print(processar_triagem("Urgente: servidor caiu no protocolo INC-9982"))

# =====================================================================
# LAB 3: CHATBOT DE E-COMMERCE COM DECISION TREE
# =====================================================================

import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier

dados_treino = [
    ("Onde esta meu pedido e qual o rastreio", "rastrear_pedido"),
    ("Quero saber a localizacao da minha encomenda", "rastrear_pedido"),
    ("Quero cancelar minha compra e pedir reembolso", "cancelar_compra"),
    ("Preciso cancelar o pedido feito ontem", "cancelar_compra"),
    ("Qual o horario de atendimento da loja fisica", "fora_escopo")
]

stopwords = ["o", "a", "meu", "minha", "e", "da", "do"]

# 1. PRÉ-PROCESSAMENTO
def pré_processar(texto):
    texto_limpo = re.sub(r'[^\w\s]', '', texto.lower()).strip()
    tokens = texto_limpo.split()

    # TODO 3.1: Filtre as stopwords da frase
    tokens_filtrados = [token for token in tokens if token not in stopwords]

    return " ".join(tokens_filtrados)

X_treino_limpo = [pré_processar(item[0]) for item in dados_treino]
y_treino = [item[1] for item in dados_treino]

# 2. VETORIZAÇÃO E TREINAMENTO (DECISION TREE)
vectorizer = TfidfVectorizer()
X_vetorizado = vectorizer.fit_transform(X_treino_limpo)

# TODO 3.2: Instancie o modelo DecisionTreeClassifier
modelo_tree = DecisionTreeClassifier()

# TODO 3.3: Treine o modelo com os dados vetorizados e os rótulos de treino
# TODO 3.3: Escreva a linha do método fit() aqui
modelo_tree.fit(X_vetorizado, y_treino)

# 3. EXTRAÇÃO DE ENTIDADE (CÓDIGO DE RASTREIO BR)
def extrair_codigo_rastreio(texto):
    # Procura códigos de rastreio como 'BR123456789'
    match = re.search(r'BR\d{9}', texto, re.IGNORECASE)

    # TODO 3.4: Se encontrar, retorne o texto correspondente em maiúsculas (match.group(0).upper()). Se não, None.
    return match.group(0).upper() if match else None

# 4. PIPELINE NLU
def processar_ecommerce(mensagem_usuario, threshold=0.50):
    texto_p = pré_processar(mensagem_usuario)
    vetor_input = vectorizer.transform([texto_p])

    # DecisionTree também calcula probabilidades com base na pureza das folhas
    probas = modelo_tree.predict_proba(vetor_input)[0]

    maior_confianca = max(probas)
    intencao_prevista = modelo_tree.classes_[probas.argmax()]

    # TODO 3.5: Crie a verificação de segurança:
    # Se maior_confianca < threshold ou intencao == "fora_escopo":
    #     retorne o dicionário de FALLBACK
    # Senão:
    #     retorne o dicionário de SUCESSO com a intenção, confiança e código de rastreio extraído
    # TODO 3.5: Escreva a condicional if/else abaixo

    if maior_confianca < threshold or intencao_prevista == "fora_escopo":
        return {
            "status": "fallback",
            "mensagem": "Solicitação fora do escopo."
        }
    else:
        return {
            "status": "sucesso",
            "intencao": intencao_prevista,
            "confianca": round(maior_confianca, 2),
            "codigo_rastreio": extrair_codigo_rastreio(mensagem_usuario)
        }

# --- TESTE 3 ---
if __name__ == "__main__":
    print(processar_ecommerce("Quero rastrear o pedido BR987654321"))
